### ISSUE TITLE
gdb_send_iter reports -EIO when client ack too early

### ISSUE THREAD

**Issue by zhangyoufu** [wkz/kmemd#2]
https://github.com/wkz/kmemd/blob/eb3f1d956e75f25000de340e8858c2a7d1211eea/src/gdb.c#L145-L151

It seems that if the client send ack(`+`) too fast, the session may broken.

**Comment by wkz** [comment]
Could you share some more details on your setup? GDB version? UNIX socket or TCP?

Do you have a GDB script or something that reproduces the issue?

**Comment by zhangyoufu** [comment]
Reproducer:
```
#!/usr/bin/env python3
import socket
import time

s = socket.create_connection(('127.0.0.1', 1234))

def send(data):
	checksum = sum(data) % 256
	payload = b'$' + data + b'#' + ('%02x' % checksum).encode()
	s.sendall(payload)

def read(addr):
	send(f'm{addr:016x},1'.encode())
	#time.sleep(0.001)
	s.sendall(b'+')

while 1:
	read(0xffff888000000000)
```

Debug Log:
```
# ./kmemd -d -s 127.1:1234
Using 'g' size of 560 bytes
Listening on 127.1:1234
Session started
RECV:"mffff888000000000,1"
SEND:"00"
...
RECV:"mffff888000000000,1"
SEND:"00"
Session ended (len:19 err:-5)
```

If uncomment `time.sleep(0.001)` in reproducer, kmemd will not report `-EIO`.

**Comment by zhangyoufu** [comment]
Using a single `FILE*` in append mode to perform both socket recv/send is far more cursed than I would expected. Write into `FILE*` could corrupt read buffer state (read/write share the same buffer and position).

**Comment by wkz** [comment]
@zhangyoufu: Do you have any authoritative source for that that you could share? Google shows me some scattered wisdom of the ancients, but nothing detailed.

**Comment by zhangyoufu** [comment]
Expected communication sequence:
```
> $request#xx
< +
< $response#xx
> +
```

In my case, I'm ignoring response and send ack(`+`) before receiving response.

Here is my understanding of the `FILE` buffer. (not sure, didn't check)
```
# after read syscall, before processing client request
<file pointer here>$request#xx+$request#xx+$request#xx+...
# after read request from buffer
$request#xx<file pointer here>+$request#xx+$request#xx+...
# send ack to client
$request#xx+<file pointer here>$request#xx+$request#xx+...
# send response to client, the file pointer advanced and points to some garbage
$request#xx+$response#xx<file pointer here>???...$request#xx+...
# read ack from client got random content inside read buffer
```

For a gdb client, previous implementation works without problem as long as gdb do not pipeline requests.
